package dev.patienty.assistant;
import dev.patienty.assistant.AssistantContext.ContextItem;import dev.patienty.encounter.*;import dev.patienty.examination.*;import dev.patienty.patient.PatientQueryService;import dev.patienty.prescription.*;import java.time.*;import java.time.temporal.ChronoUnit;import java.util.*;import org.springframework.stereotype.Component;
@Component public class ContextBuilder {private final PatientQueryService patients;private final EncounterRepository encounters;private final ExaminationResultRepository examinations;private final PrescriptionItemRepository prescriptions;private final Clock clock=Clock.systemUTC();
    public ContextBuilder(PatientQueryService patients,EncounterRepository encounters,ExaminationResultRepository examinations,PrescriptionItemRepository prescriptions){this.patients=patients;this.encounters=encounters;this.examinations=examinations;this.prescriptions=prescriptions;}
    public AssistantContext build(UUID id,AssistantIntent intent,String question){patients.requireAssigned(id);Instant after=clock.instant().minus(183,ChronoUnit.DAYS);List<ContextItem> items=new ArrayList<>();
        if(intent==AssistantIntent.RECENT_CHANGES||intent==AssistantIntent.ENCOUNTER_TIMELINE)encounters.findByPatientIdAndStatusAndOccurredAtAfterOrderByOccurredAtDesc(id,"COMPLETED",after).stream().limit(20).map(ContextBuilder::encounter).forEach(items::add);
        if(intent==AssistantIntent.RECENT_CHANGES||intent==AssistantIntent.RECENT_EXAMINATIONS||intent==AssistantIntent.MEASUREMENT_TREND)examinations.findMeasurements(id,intent==AssistantIntent.MEASUREMENT_TREND?metric(question):"",after,clock.instant()).stream().limit(50).map(ContextBuilder::measurement).forEach(items::add);
        if(intent==AssistantIntent.RECENT_CHANGES||intent==AssistantIntent.MEDICATION_CHANGES){Map<UUID,PrescriptionRecord> unique=new LinkedHashMap<>();for(PrescriptionRecord r:prescriptions.findRecent(id,after))unique.putIfAbsent(r.prescriptionId(),r);unique.values().stream().limit(10).map(ContextBuilder::prescription).forEach(items::add);}
        items.sort(Comparator.comparing(ContextItem::occurredAt).reversed());return new AssistantContext(id,List.copyOf(items));}
    private static ContextItem encounter(Encounter e){return new ContextItem("encounter:"+e.getId(),"ENCOUNTER",e.getOccurredAt(),"진료 기록",Map.of("departmentCode",e.getDepartmentCode(),"chiefComplaint",Objects.toString(e.getChiefComplaint(),"")));}
    private static ContextItem measurement(MeasurementRecord r){Map<String,String>f=new LinkedHashMap<>();f.put("metricCode",r.metricCode());f.put("displayName",r.displayName());f.put("value",r.value().stripTrailingZeros().toPlainString());f.put("unit",Objects.toString(r.unit(),""));f.put("abnormalFlag",r.abnormalFlag());return new ContextItem(r.evidenceId(),"EXAMINATION_RESULT",r.occurredAt(),r.displayName()+" 검사 결과",f);}
    private static ContextItem prescription(PrescriptionRecord r){return new ContextItem(r.evidenceId(),"PRESCRIPTION",r.prescribedAt(),"처방 기록",Map.of("status",r.status(),"medication",r.medicationName()));}
    private static String metric(String question){String q=question.toLowerCase(Locale.ROOT);if(q.contains("혈압")||q.contains("blood pressure"))return "BP_SYSTOLIC";if(q.contains("혈당")||q.contains("glucose"))return "GLUCOSE_FASTING";if(q.contains("콜레스테롤")||q.contains("cholesterol"))return "TOTAL_CHOLESTEROL";return "";}}
